import React,{useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Menu,X,ArrowRight,MessageCircle,Phone,Mail,MapPin,Download,Briefcase,GraduationCap,Boxes,ShoppingBasket,Building2,ChevronDown} from 'lucide-react'
import './styles.css'

const A='/images/'
const products=[
 {name:'Concrete Blocks',cat:'BLOCKS',img:A+'blocks.jpg',desc:'Concrete blocks for construction-related needs.',fallback:'Contact for current price'},
 {name:'Cement',cat:'CEMENT',img:A+'cement.jpg',desc:'Cement supplied for construction needs.',fallback:'Contact for current price'},
 {name:'Provision Store',cat:'PROVISION STORE',img:A+'provision-store.jpg',desc:'Provision-store products and everyday essentials.',fallback:'Contact for availability and current prices'},
]
const gallery=[
 {img:A+'graduation-memories.jpg',cat:'MY PHOTOS',title:'Graduation memories'},
 {img:A+'life-learning.jpg',cat:'MY JOURNEY',title:'Learning & early experience'},
 {img:A+'community-journey.jpg',cat:'MY JOURNEY',title:'Community journey'},
 {img:A+'nysc-journey.jpg',cat:'MY JOURNEY',title:'NYSC journey'},
 {img:A+'college-photo.jpg',cat:'MY PHOTOS',title:'College memories'},
 {img:A+'blocks.jpg',cat:'BLOCK PRODUCTION',title:'Concrete blocks'},
 {img:A+'cement.jpg',cat:'CEMENT',title:'Cement'},
 {img:A+'provision-store.jpg',cat:'PROVISION STORE',title:'Provision store'},
]
const quick=['Blocks','Cement','Building Materials','Provision Store','About Nkiruka','Contact Us']
function Chat(){const [open,setOpen]=useState(false),[text,setText]=useState(''),[msgs,setMsgs]=useState([{r:'a',t:"Hello! 👋 Welcome to FASA Excel Global Enterprise. I can help with information about the business and Ochiagha Nkiruka Favour."}]),[loading,setLoading]=useState(false)
 const fallback=q=>{q=q.toLowerCase(); if(q.includes('block')) return 'FASA Excel Global Enterprise provides blocks. Contact us for current prices and availability.'; if(q.includes('cement')) return 'FASA Excel Global Enterprise provides cement. Contact us for current prices and availability.'; if(q.includes('provision')) return 'The business includes a provision store. Contact us for product availability and current prices.'; if(q.includes('nkiruka')||q.includes('about')) return 'Ochiagha Nkiruka Favour is presented on this site as a professional, entrepreneur and continuous learner. Please see the About, Career and Education sections for supplied details.'; if(q.includes('contact')||q.includes('whatsapp')) return 'Please use the Contact section or the WhatsApp button on the website to make an enquiry.'; return 'I can help with blocks, cement, building materials, provision store information, and the professional profile on this website.'}
 const send=async(q=text)=>{if(!q.trim())return; setMsgs(m=>[...m,{r:'u',t:q}]);setText('');setLoading(true);try{const h=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[...msgs.filter(x=>x.r==='u'||x.r==='a').map(x=>({role:x.r==='u'?'user':'assistant',content:x.t})),{role:'user',content:q}]})}); if(h.ok){const d=await h.json();setMsgs(m=>[...m,{r:'a',t:d.reply}])}else throw 0}catch{setMsgs(m=>[...m,{r:'a',t:fallback(q)}])}finally{setLoading(false)}}
 return <><button className="chat-fab" onClick={()=>setOpen(!open)} aria-label="Open FASA AI Assistant"><MessageCircle size={24}/></button>{open&&<div className="chat"><div className="chat-head"><div><strong>FASA AI Assistant</strong><small>Business & profile help</small></div><button onClick={()=>setOpen(false)} aria-label="Close chat"><X size={18}/></button></div><div className="chat-body">{msgs.map((m,i)=><div key={i} className={'bubble '+m.r}>{m.t}</div>)}{loading&&<div className="bubble a">Thinking…</div>}<div className="quick">{quick.map(q=><button key={q} onClick={()=>send(q)}>{q}</button>)}</div></div><div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Type your message…"/><button onClick={()=>send()} aria-label="Send message"><ArrowRight size={18}/></button></div></div>}
 </>}
function Nav(){const [open,setOpen]=useState(false);const links=[['Home','home'],['About Me','about'],['My Story','story'],['Career','career'],['Education & Skills','education'],['Business','business'],['Products','products'],['Gallery','gallery'],['Contact','contact']];return <nav><div className="nav-inner"><a className="brand" href="#home"><span className="brand-mark">FX</span><span><b>OCHIAGHA<br/>NKIRUKA FAVOUR</b><small>Professional Profile & Entrepreneur</small></span></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className={'links '+(open?'show':'')}>{links.map(([t,id])=><a key={id} href={'#'+id} onClick={()=>setOpen(false)}>{t}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setOpen(false)}>CONTACT ME</a></div></div></nav>}
function Section({id,eyebrow,title,children}){return <section id={id} className="section"><div className="wrap"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{children}</div></section>}
function App(){const [filter,setFilter]=useState('ALL'), filtered=filter==='ALL'?gallery:gallery.filter(g=>g.cat===filter);return <div><Nav/><header id="home" className="hero"><div className="hero-copy"><div className="eyebrow">Professional • Entrepreneur • Continuous Learner</div><h1>Ochiagha<br/><span>Nkiruka Favour</span></h1><p>A professional profile and entrepreneurial journey built around continuous learning, service, technology and business.</p><div className="business-line"><b>FASA Excel Global Enterprise</b><span>Blocks • Cement • Building Materials • Provision Store</span></div><div className="actions"><a href="#about">VIEW MY PROFILE</a><a href="#story">MY LIFE STORY</a><a className="gold" href="#business">EXPLORE MY BUSINESS</a><a href="#products">VIEW PRODUCTS</a><a href="#contact">CONTACT ME</a><a className="gold" href="#contact">WHATSAPP US</a></div></div><div className="hero-photo"><img src={A+'graduation-memories.jpg'} alt="Ochiagha Nkiruka Favour graduation memories"/></div></header>
<Section id="about" eyebrow="WHO I AM" title="Professional Profile"><div className="two"><div><h3>Professional, entrepreneurial and continuously developing</h3><p>This website brings together Ochiagha Nkiruka Favour’s professional profile, career journey, education and entrepreneurial path. Content is based on the supplied materials; no additional experience or qualifications are assumed.</p><div className="cards"><div><Briefcase/> <b>Career</b><span>Explore the supplied employment history.</span></div><div><GraduationCap/><b>Education</b><span>View the supplied academic and learning background.</span></div><div><Boxes/><b>Enterprise</b><span>Discover FASA Excel Global Enterprise.</span></div></div></div><img className="portrait" src={A+'college-photo.jpg'} alt="Personal photograph from the supplied collection"/></div></Section>
<Section id="story" eyebrow="MY JOURNEY" title="My Life Story"><div className="story"><div><p>My life story section is designed to grow from the supplied life-story document, connecting education, work, learning and entrepreneurship into one authentic journey.</p><div className="timeline"><div><b>Educational beginnings</b><span>Learning and academic milestones from the supplied documents.</span></div><div><b>Professional journey</b><span>Work and service experiences documented in the CV.</span></div><div><b>Continuous learning</b><span>Skills, professional development and technology interests.</span></div><div><b>Entrepreneurial path</b><span>FASA Excel Global Enterprise and the business journey.</span></div></div></div><div className="story-grid">{gallery.slice(0,4).map(g=><img key={g.img} src={g.img} alt={g.title}/>)}</div></div></Section>
<Section id="career" eyebrow="EXPERIENCE" title="My Professional Journey"><div className="notice">Career details are kept aligned with the supplied CV. Update the source CV and this section when you want to publish additional verified details.</div><div className="career-grid">{['Store Manager and POS Operator','Computer Operator and POS Operator','Classroom Teacher','Home Lesson Teacher','HMO Officer & Secretary','Café Manager','Computer Operator and Sales Manager','Computer Instructor'].map((x,i)=><article key={i}><span>0{i+1}</span><h3>{x}</h3><p>Responsibilities and dates: see the supplied professional CV.</p></article>)}</div></Section>
<Section id="education" eyebrow="LEARNING" title="Education & Skills"><div className="edu"><div className="edu-list">{['NABTEB','OND in Computer Science','HND in Computer Science','Post Graduate Diploma in Education','Grade 1–6 Music Theory & Classical Singing'].map(x=><div key={x}><GraduationCap/><span>{x}</span></div>)}</div><div><h3>Skills</h3><div className="skill-tags">{['Microsoft Office','Document Imaging and Scanning','Acrobat Reader','Graphics Design','Artificial Intelligence','Software Development'].map(x=><span key={x}>{x}</span>)}</div><h3>Professional qualities</h3><p>See the supplied CV for the complete skills, language skills and personal competencies.</p></div></div></Section>
<Section id="business" eyebrow="FASA EXCEL GLOBAL ENTERPRISE" title="My Entrepreneurial Path"><p className="lead">Beyond my professional journey, I am also building my entrepreneurial path through FASA Excel Global Enterprise.</p><div className="business-grid">{products.map(p=><article key={p.name}><img src={p.img} alt={p.name}/><div><span className="cat">{p.cat}</span><h3>{p.name}</h3><p>{p.desc}</p><a href="#contact">ENQUIRE NOW <ArrowRight size={16}/></a></div></article>)}</div></Section>
<Section id="products" eyebrow="PRODUCT CATALOGUE" title="Products & Services"><div className="filters">{['ALL','BLOCKS','CEMENT','BUILDING MATERIALS','PROVISION STORE'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="product-grid">{(filter==='BUILDING MATERIALS'?products:products.filter(p=>filter==='ALL'||p.cat===filter)).map(p=><article key={p.name}><img src={p.img} alt={p.name}/><div><span className="cat">{p.cat}</span><h3>{p.name}</h3><p>{p.desc}</p><b>{p.fallback}</b><a href="#contact">ENQUIRE NOW</a></div></article>)}</div></Section>
<Section id="gallery" eyebrow="PHOTO GALLERY" title="My Photos & Journey"><div className="filters">{['ALL','MY PHOTOS','MY JOURNEY','BLOCK PRODUCTION','CEMENT','PROVISION STORE'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="gallery">{filtered.map((g,i)=><figure key={i}><img src={g.img} alt={g.title}/><figcaption>{g.title}<small>{g.cat}</small></figcaption></figure>)}</div></Section>
<Section id="contact" eyebrow="LET'S CONNECT" title="Contact"><div className="contact"><div><h3>Ready to make an enquiry?</h3><p>Use the contact form or WhatsApp call-to-action. Current prices, availability and other details should be confirmed directly with FASA Excel Global Enterprise.</p><div className="contact-items"><div><Mail/> <span>Email<br/><b>nki4real@gmail.com</b></span></div></div><a className="download" href="/docs/Ochiagha-Nkiruka-Favour-CV-and-Life-Story.docx" download><Download size={18}/> DOWNLOAD CV & LIFE STORY</a></div><form onSubmit={e=>{e.preventDefault();alert('Thank you. Please connect through WhatsApp or the supplied email to complete your enquiry.')}}><input required placeholder="FULL NAME"/><input required placeholder="PHONE NUMBER"/><input type="email" placeholder="EMAIL"/><select><option>PRODUCT / SERVICE</option><option>Blocks</option><option>Cement</option><option>Building Materials</option><option>Provision Store</option></select><input placeholder="QUANTITY"/><textarea rows="5" placeholder="MESSAGE"></textarea><button>SEND ENQUIRY <ArrowRight size={17}/></button></form></div></Section>
<footer><div><b>OCHIAGHA NKIRUKA FAVOUR</b><p>Professional Profile & Entrepreneur</p></div><div><b>FASA EXCEL GLOBAL ENTERPRISE</b><p>Blocks • Cement • Building Materials • Provision Store</p></div><div className="footlinks">{['Home','About','My Story','Career','Business','Products','Gallery','Contact'].map(x=><a href={'#'+x.toLowerCase().replaceAll(' ','') } key={x}>{x}</a>)}</div><p className="copyright">© 2026 FASA Excel Global Enterprise. All Rights Reserved.</p></footer><Chat/></div>}
createRoot(document.getElementById('root')).render(<App/>)
